### DISCUSSION TITLE
Anyone  configured connaisseur with private acr and docker content trust?

### DISCUSSION THREAD

**Discussion by amitsaurabh32** [sse-secure-systems/connaisseur#1316] [Q&A]
Hi All,

Can anyone suggest what are all the changes we need to perform in values.yml file in order to configure connaisseur with private acr?

**Comment by xopham** [comment]
@amitsaurabh32 this was tested some time ago, but there is dedicated information on this in the docs: https://sse-secure-systems.github.io/connaisseur/v3.1.1/validators/notaryv1/#using-azure-container-registry

Hope it still works 🙏

**Reply by amitsaurabh32** [reply]
Hi @xopham,

yes following the same document but still getting the below error, As per the error log it says unauthorized even after adding auth.user and auth.password in the values.yaml for the service principal which have reader access to our private acr repository. Could you please help me to solve this?


kubectl logs connaisseur-deployment-88c49dd4b-gh4z8 -n connaisseur

{"timestamp": "2023-10-17 08:14:35.268463", "message": "Traceback (most recent call last):\n  File \"/app/connaisseur/flask_application
.py\", line 120, in __async_mutate\n    response = await __admit(admission_request, session)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^\n  File \"/app/connaisseur/flask_application.py\", line 152, in __admit\n    await patches\n  File \"/usr/local/lib/pyt
hon3.11/asyncio/tasks.py\", line 349, in __wakeup\n    future.result()\n  File \"/usr/local/lib/python3.11/asyncio/tasks.py\", line 279
, in __step\n    result = coro.throw(exc)\n             ^^^^^^^^^^^^^^^\n  File \"/app/connaisseur/flask_application.py\", line 247, in
 __validate_image\n    trusted_digest = await validator.validate(image, **validator_arguments)\n                     ^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/connaisseur/validators/notaryv1/notaryv1_validator.py\", line 50, in validate\n    
signed_image_targets = await self.__process_chain_of_trust(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"
/app/connaisseur/validators/notaryv1/notaryv1_validator.py\", line 121, in __process_chain_of_trust\n    trust_data_list = await asynci
o.gather(\n                      ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/tasks.py\", line 349, in __wakeup\n 
   future.result()\n  File \"/usr/local/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n    result = coro.send(None)\n         
    ^^^^^^^^^^^^^^^\n  File \"/app/connaisseur/validators/notaryv1/notary.py\", line 122, in get_trust_data\n    token = await self.__g
et_auth_token(session, auth_url)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/connaisseur/validators/nota
ryv1/notary.py\", line 232, in __get_auth_token\n    response.raise_for_status()\n  File \"/usr/local/lib/python3.11/site-packages/aioh
ttp/client_reqrep.py\", line 1005, in raise_for_status\n    raise ClientResponseError(\naiohttp.client_exceptions.ClientResponseError: 
401, message='Unauthorized', url=URL('https://xxxxxxxxxxxxxxxxxxxxxxxx.azurecr.io/oauth2/token?service=xxxxxxxxxxxxxxxxxxx.azurecr.io&scop
e=repository:xxxxxxxxxxxxxxxxxxxxxxx.azurecr.io/connaisseur-test1:pull')\n"}
{"timestamp": "2023-10-17 08:14:35.269689", "client_ip": "10.244.0.1", "method": "POST", "path": "/mutate", "query": "timeout=30s", "pr
otocol": "HTTP/1.1", "status_code": "200"}

**Reply by xopham** [reply]
It is actually problematic that Connaisseur fails uncontrolled which should have been caught, I believe. @phbelitz ?

As for the problem: have you tried checking the trust data locally via docker cli using those same credentials? Something like:
```bash
docker trust inspect --pretty xxxxxxxxxxxxxxxxxxxxxxx.azurecr.io/connaisseur-test1:pull
```

**Reply by xopham** [reply]
please consider providing (a redacted) excerpt of your helm configuration for better debugging

**Reply by amitsaurabh32** [reply]
Hi @xopham,

yes, I have verified the signature using "docker trust inspect --pretty xxxxxxxxxxxxxxxxxxxxxxx.azurecr.io/connaisseur-test1:imagetag" and able to view the signatures.

Please find below the changes we have done in our values.yml to install connaisseur.

  validators:
    - name: myvnvacr-validator
      isAcr: true
      type: notaryv1
      host: xxxxxxxxxxxxxxxxxxx.azurecr.io
      trustRoots:
        - name: myvnvacr-validator
          key:  |
            -----BEGIN PUBLIC KEY-----
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            -----END PUBLIC KEY-----
          auth:
            username: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
			
policy:
    - pattern: "xxxxxxxxxxxxxxxxxxxxxxx.azurecr.io/*:*"
      validator: myvnvacr-validator
      with:
        trustRoot: myvnvacr-validator

**Reply by xopham** [reply]
Which Connaisseur Version are you on?

Either way, if not unclearly redacted, the following policy pattern would seem to be incorrect:

```yaml
policy:
- pattern: "xxxxxxxxxxxxxxxxxxxxxxx.azurecr.io/:"
```

Should be more like:
```yaml
policy:
- pattern: "xxxxxxxxxxxxxxxxxxxxxxx.azurecr.io/*"
```
This could have caused the unauthorized exception, as Connaisseur might have not applied it. I was actually wondering why Connaisseur would show a `200 - OK` sttus code in the log right after, as validation failed

**Reply by amitsaurabh32** [reply]
Hi @xopham,

I have changed the policy pattern like 
policy:
- pattern: "xxxxxxxxxxxxxxxxxxxxxxx.azurecr.io/*"


But still getting the same authorization error.

**Reply by xopham** [reply]
What happens if you change it to definitely not match? Like the domain or something?

**Reply by amitsaurabh32** [reply]
Hi @xopham,

After changing the policy pattern i am getting the same unauthorized error, could you please suggest what permission connaisseur is expecting for our private repository,  I have added auth.username and auth.password of the service principle which have reader permission for acr repository.

And we haven't configured any notary server for our acr so should we use type: notaryv1 for our validator or not ?

If Not what should be the type of our validator in case of acr ?

validators:
- name: myvnvacr-validator
isAcr: true
type: notaryv1

**Reply by xopham** [reply]
Let's recap. You are using the following policy:
```yaml
validators:
- name: myvnvacr-validator
isAcr: true
type: notaryv1
host: xxxxxxxxxxxxxxxxxxx.azurecr.io
trustRoots:
- name: myvnvacr-validator
key: |
-----BEGIN PUBLIC KEY-----
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-----END PUBLIC KEY-----
auth:
username: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

policy:
- pattern: "xxxxxxxxxxxxxxxxxxxxxxx.azurecr.io/:"
validator: myvnvacr-validator
with:
trustRoot: myvnvacr-validator
```
I understand there is no other `validators` or `policy` pattern configured, right?

When you change the pattern:
```yaml
validators:
- name: myvnvacr-validator
isAcr: true
type: notaryv1
host: xxxxxxxxxxxxxxxxxxx.azurecr.io
trustRoots:
- name: myvnvacr-validator
key: |
-----BEGIN PUBLIC KEY-----
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-----END PUBLIC KEY-----
auth:
username: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

policy:
- pattern: "yyyyyyyyyyyyyyyyyyyy.azurecr.io/:"
validator: myvnvacr-validator
with:
trustRoot: myvnvacr-validator
```
You still get `Unauthorized`?
That would seem to indicate that your configured validator is never applied. Essentially, Connaisseur matches the image against the policies and if one matches, it will apply the validator. Now, changing the policy pattern should have shifted you from matched to not-matched, but the msg remains the same, right?

**Reply by amitsaurabh32** [reply]
Hi @xopham,

yes, correct there is no other validator and policy pattern is configured, And yes I am still getting Unauthorized error but one more strange error I have observed from the first error log which i have shared below as well.

ryv1/notary.py", line 232, in __get_auth_token\n response.raise_for_status()\n File "/usr/local/lib/python3.11/site-packages/aioh
ttp/client_reqrep.py", line 1005, in raise_for_status\n raise ClientResponseError(\naiohttp.client_exceptions.ClientResponseError:
401, message='Unauthorized', url=URL('https://xxxxxxxxxxxxxxxxxxxxxxxx.azurecr.io/oauth2/token?service=xxxxxxxxxxxxxxxxxxx.azurecr.io&scop
e=repository:xxxxxxxxxxxxxxxxxxxxxxx.azurecr.io/connaisseur-test1:pull')\n"}
{"timestamp": "2023-10-17 08:14:35.269689", "client_ip": "10.244.0.1", "method": "POST", "path": "/mutate", "query": "timeout=30s", "pr
otocol": "HTTP/1.1", "status_code": "200"}


If you observe the repository url "repository:xxxxxxxxxxxxxxxxxxxxxxx.azurecr.io/connaisseur-test1:pull'" its structure should be myacr.azure.io/repositoryname:tagname  . But in the error log tag name is appearing as pull instead of my original tag name. Could you please advise if this is expected or there is something wrong with this.

**Reply by xopham** [reply]
Can't actively test right now. Could you check what happens if you push an image with tag "pull" and repeat?
Here, is the strange thing: If your pattern does not match, your configured validator is not used. Let's test that. Could you extend your configuration with the following entries:
```yaml
application:
  validators:
  - name: deny
    type: static
    approve: false
  policy:
    - pattern: "*:*"
      validator: deny
```
In this case, your pod should not meet your specific pattern and fall back to this one and be denied bc it is set to be default denied. this should result in:
```bash
Error from server: admission webhook "connaisseur-svc.connaisseur.svc" denied the request: Static deny.
```
