### DISCUSSION TITLE
Auth - Secret Name

### DISCUSSION THREAD

**Discussion by bally-singh** [sse-secure-systems/connaisseur#261] [Q&A] [answered]
Hi Team!

Hope you can help with this one... so I created the auth.yaml file:

username: "testuser"
password: "password123"

ran the following command:

kubectl create secret generic **connaisseursecret** --from-file auth.yaml

I updated the values.yaml:

&#35;cert: |  &#35; in case the trust data host is using a selfsigned certificate
&#35;  -----BEGIN CERTIFICATE-----
&#35;  ...
&#35;  -----END CERTIFICATE-----
 auth:  &#35; credentials in case the trust data requires authentication
&#35; &#35; either (preferred solution)
  secret_name: **connaisseursecret**  &#35; reference a k8s secret in the form required by the validator type (check the docs)
&#35;  &#35; or (only for notaryv1 validator)
&#35;  username: myuser
&#35;  password: mypass

but when I run:

helm install connaisseur helm --atomic --create-namespace --namespace connaisseur

I get the error message:

Error: release connaisseur failed, and has been uninstalled due to atomic being set: timed out waiting for the condition

What is the correct formatting for the values.yaml?

**Comment by xopham** [comment, marked as answer]
Hey @bally-singh :wave: what you are doing looks correct to me on first sight. The `secret_name` must be indented however:

```yaml
#cert: | # in case the trust data host is using a selfsigned certificate
# -----BEGIN CERTIFICATE-----
# ...
# -----END CERTIFICATE-----
auth: # credentials in case the trust data requires authentication
# # either (preferred solution)
  secret_name: connaisseursecret # reference a k8s secret in the form required by the validator type (check the docs)
# # or (only for notaryv1 validator)
# username: myuser
# password: mypass
```

In case, that is only a copy-paste issue, my second best guess would be that you might have created the secret in another namespace other than the connaisseur namespace in which case Connaisseur cannot access it. Is that possible? I think we should make this transparent in the docs in any case :thinking: 

If that does not solve your problem: what do you get, when doing `connaisseur-deployment-<your pod ID>` while connaisseur tries to install. That might help to further debug
