### DISCUSSION TITLE
Cannot connect to host notary-server.myintradomain.com:4443 ssl:True [SSLCertVerificationError: (1, '[ SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]

### DISCUSSION THREAD

**Discussion by shaktigupta200** [sse-secure-systems/connaisseur#306] [Q&A] [answered]
Hi all,

I have the following setup -

(1) Private Notary server on HTTPS (PKI created and signed through Aws Private CA)
(2) Connaisseur running properly on AWS EKS.
(3) AWS ECR as registry service

Public root key generated for Registry and added in config.

> Below is my Helm config
```
deployment:
  replicasCount: 1
  image: securesystemsengineering/connaisseur:v2.1.2
  helmHookImage: securesystemsengineering/connaisseur:helm-hook-v1.1
  imagePullPolicy: Always
  failurePolicy: Fail 
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - connaisseur
            topologyKey: kubernetes.io/hostname
          weight: 100

service:
  type: ClusterIP
  port: 443

validators:
- name: allow
  type: static
  approve: true
- name: deny
  type: static
  approve: false
- name:shared-notary
  type: notaryv1 
  host: notary-server.myintradomain.com:4443 
  selfsigned: true
  trust_roots:
  - name: my-validate
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERSHE1LSbuBc7MhM5na6nbihQ//WN
      H+8ksL3c4Uo/DxI3RARyUJDyn74/RW0CCsRFdVWtg8GCo56+HKG32Ls4XA==
      -----END PUBLIC KEY-----

    cert: |
      -----BEGIN CERTIFICATE-----
      < Notary Public Key here >
      -----END CERTIFICATE-----

- name: dockerhub_basics
  type: notaryv1
  host: notary.docker.io
  trust_roots:
  - name: docker_official
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOXYta5TgdCwXTCnLU09W5T4M4r9f
      QQrqJuADP6U7g5r9ICgPSmZuRHP/1AYUfOQW3baveKsT969EfELKj1lfCA==
      -----END PUBLIC KEY-----
  - name: securesystemsengineering_official
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsx28WV7BsQfnHF1kZmpdCTTLJaWe
      d0CA+JOi8H4REuBaWSZ5zPDe468WuOJ6f71E7WFg3CVEVYHuoZt2UYbN/Q==
      -----END PUBLIC KEY-----

policy:
- pattern: "*:*"
- pattern: "docker.io/library/*:*"
  validator: dockerhub_basics
  with:
    trust_root: docker_official
- pattern: "1xxxxxxx0.dkr.ecr.amazonaws.com/poc_repo:*"
  validator: shared-notary
  with:
    trust_root: my-validate
- pattern: "k8s.gcr.io/*:*"
  validator: allow
- pattern: "docker.io/securesystemsengineering/*:*"
  validator: dockerhub_basics
  with:
    trust_root: securesystemsengineering_official
detectionMode: false

namespacedValidation:
  enabled: false
  mode: ignore
```

While creating deployment using kubectl utility, I am getting following exception in my console.

> kubectl apply -f test_deployment_signed.yaml
> Error from server: error when creating "test_deployment_signed.yaml": admission webhook "connaisseur-svc.connaisseur.svc" denied the request: unknown error. please check the logs.

While checking the connaisseur pod logs, getting below error.

> Traceback (most recent call last):
>   File "/app/connaisseur/flask_server.py", line 53, in mutate
>     response = __admit(admission_request)
>   File "/app/connaisseur/flask_server.py", line 167, in __admit
>     trusted_digest = validator.validate(image, **policy_rule.arguments)
>   File "/app/connaisseur/validators/notaryv1/notaryv1_validator.py", line 44, in validate
>     signed_image_targets = asyncio.run(
>   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/app/connaisseur/validators/notaryv1/notaryv1_validator.py", line 115, in __process_chain_of_trust
>     trust_data_list = await asyncio.gather(
>   File "/app/connaisseur/validators/notaryv1/notary.py", line 109, in get_trust_data
>     async with session.get(**request_kwargs) as response:
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
>     self._resp = await self._coro
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
>     conn = await self._connector.connect(
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
>     proto = await self._create_connection(req, traces, timeout)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
>     _, proto = await self._create_direct_connection(req, traces, timeout)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
>     raise last_exc
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
>     transp, proto = await self._wrap_create_connection(
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
>     raise ClientConnectorCertificateError(req.connection_key, exc) from exc
> **aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host notary-server.myintradomain.com:4443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]**

Please suggest how can I fix.

**Comment by xopham** [comment, marked as answer]
Hi @shaktigupta200 :wave: 
On first sight, I looks like an indentation error in your validator config:
```yaml
- name:shared-notary
  type: notaryv1 
  host: notary-server.myintradomain.com:4443 
  selfsigned: true
  trust_roots:
  - name: my-validate
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERSHE1LSbuBc7MhM5na6nbihQ//WN
      H+8ksL3c4Uo/DxI3RARyUJDyn74/RW0CCsRFdVWtg8GCo56+HKG32Ls4XA==
      -----END PUBLIC KEY-----

    cert: |
      -----BEGIN CERTIFICATE-----
      < Notary Public Key here >
      -----END CERTIFICATE-----
```
It seems that `cert` is indented too much. The `cert` key is part of the validator not trust roots configuration, i.e. should be `validators[*].cert` NOT `validators[*].trust_roots[*].cert`. The correct configuration would be:
```yaml
- name:shared-notary
  type: notaryv1 
  host: notary-server.myintradomain.com:4443 
  selfsigned: true
  trust_roots:
  - name: my-validate
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERSHE1LSbuBc7MhM5na6nbihQ//WN
      H+8ksL3c4Uo/DxI3RARyUJDyn74/RW0CCsRFdVWtg8GCo56+HKG32Ls4XA==
      -----END PUBLIC KEY-----

  cert: |
    -----BEGIN CERTIFICATE-----
    < Notary Public Key here >
    -----END CERTIFICATE-----
```
Please also note, that the cert should be in pem format as described in the docs [here](https://sse-secure-systems.github.io/connaisseur/v2.1.2/validators/notaryv1/#configuration-options).
In addition, the `selfsigned` key does not exist anymore. Is that still lingering around somewhere in the docs or where did you find it?

Let me know if that helps :slightly_smiling_face:

**Comment by shaktigupta200** [comment]
Hi @xopham , thanks for the prompt response. I have now corrected the values.yaml and the current config is mentioned below. 

```
deployment:
  replicasCount: 1
  image: securesystemsengineering/connaisseur:v2.1.2
  helmHookImage: securesystemsengineering/connaisseur:helm-hook-v1.1
  imagePullPolicy: Always
  failurePolicy: Fail 
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - connaisseur
            topologyKey: kubernetes.io/hostname
          weight: 100

service:
  type: ClusterIP
  port: 443

validators:
- name: allow
  type: static
  approve: true
- name: deny
  type: static
  approve: false
- name:shared-notary
  type: notaryv1 
  host: notary-server.myintradomain.com:4443
  trust_roots:
  - name: my-validate
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERSHE1LSbuBc7MhM5na6nbihQ//WN
      H+8ksL3c4Uo/DxI3RARyUJDyn74/RW0CCsRFdVWtg8GCo56+HKG32Ls4XA==
      -----END PUBLIC KEY-----

  cert: |
    -----BEGIN CERTIFICATE-----
    < Notary Public Key here >
    -----END CERTIFICATE-----

- name: dockerhub_basics
  type: notaryv1
  host: notary.docker.io
  trust_roots:
  - name: docker_official
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOXYta5TgdCwXTCnLU09W5T4M4r9f
      QQrqJuADP6U7g5r9ICgPSmZuRHP/1AYUfOQW3baveKsT969EfELKj1lfCA==
      -----END PUBLIC KEY-----
  - name: securesystemsengineering_official
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsx28WV7BsQfnHF1kZmpdCTTLJaWe
      d0CA+JOi8H4REuBaWSZ5zPDe468WuOJ6f71E7WFg3CVEVYHuoZt2UYbN/Q==
      -----END PUBLIC KEY-----

policy:
- pattern: "*:*"
- pattern: "docker.io/library/*:*"
  validator: dockerhub_basics
  with:
    trust_root: docker_official
- pattern: "1xxxxxxx0.dkr.ecr.amazonaws.com/poc_repo:*"
  validator: shared-notary
  with:
    trust_root: my-validate
- pattern: "k8s.gcr.io/*:*"
  validator: allow
- pattern: "docker.io/securesystemsengineering/*:*"
  validator: dockerhub_basics
  with:
    trust_root: securesystemsengineering_official
detectionMode: false

namespacedValidation:
  enabled: false
  mode: ignore
```

I have used below commands to sign image and pushed to AWS Elastic Container Registry.

- docker trust key generate root_signer
- docker trust signer add --key /root/root_signer.pub root_signer xxxxxx.dkr.ecr.amazonaws.com/poc_repo
- docker tag nginx:latest xxxxxx.dkr.ecr.amazonaws.com/poc_repo:signed
- docker push xxxxxx.dkr.ecr.amazonaws.com/poc_repo:signed

When pulling image to local when DCT enabled, I can see image is signed by Notary server.


But when creating a new deployment using kubectl, I am getting below error.

> kubectl apply -f test_deployment_signed.yaml
> Error from server: error when creating "test_deployment_signed.yaml": admission webhook "connaisseur-svc.connaisseur.svc" denied the request: Failed to verify signature of
>  trust data root.

And connaisseur pod logs are 

> [2021-09-12 07:40:28,316] INFO: No alerting configuration file found.To use the alerting feature you need to run `make upgrade`in a freshly pulled Connaisseur repository.
> [2021-09-12 07:40:28,316] ERROR: {'message': 'Failed to verify signature of trust data root.', 'context': {'trust_data_kind': 'root', 'detection_mode': False, 'user': 'kubernetes-admin', 'operation': 'CREATE', 'kind': 'Deployment', 'name': 'nginx-dep-4', 'namespace': 'shared-perf', 'image': 'xxxxxx.dkr.ecr.amazonaws.com/poc_repo:signed'}}


Please suggest.

**Comment by xopham** [comment]
@shaktigupta200 the error message `Failed to verify signature of trust data root.` indicates that the root public key used for the image does not match the public key provided in the validator configuration:
```yaml
- name:shared-notary
  type: notaryv1 
  host: notary-server.myintradomain.com:4443
  trust_roots:
  - name: my-validate
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERSHE1LSbuBc7MhM5na6nbihQ//WN
      H+8ksL3c4Uo/DxI3RARyUJDyn74/RW0CCsRFdVWtg8GCo56+HKG32Ls4XA==
      -----END PUBLIC KEY-----
(...)
```
Now to troubleshoot...

> I have used below commands to sign image and pushed to AWS Elastic Container Registry.
> docker trust key generate root_signer
> docker trust signer add --key /root/root_signer.pub root_signer xxxxxx.dkr.ecr.amazonaws.com/poc_repo
> docker tag nginx:latest xxxxxx.dkr.ecr.amazonaws.com/poc_repo:signed
> docker push xxxxxx.dkr.ecr.amazonaws.com/poc_repo:signed

I assume you have set the DCT environment variables (`DOCKER_CONTENT_TRUST=1` and `DOCKER_CONTENT_TRUST_SERVER=https://notary-server.myintradomain.com:4443`) to sign the image upon push? Otherwise, the described commands would not yield a signed image in your repo with the signature at `notary-server.myintradomain.com:4443`.

With your commands you are adding a new signer to the repo. However, that signer might not be the root which is required for verification. Is the key provided in the config above the public key of `/root/root_signer.pub`? From what it looks like the `root_signer` is just added as a delegation. You can check that via:
```bash
docker trust inspect --pretty 1xxxxxxx0.dkr.ecr.amazonaws.com/poc_repo
```
For Connaisseur this for example yields:
```bash
$ docker trust inspect --pretty docker.io/securesystemsengineering/connaisseur

Signatures for docker.io/securesystemsengineering/connaisseur

SIGNED TAG       DIGEST                                                             SIGNERS
helm-hook        13f7d16022db873a22a5c1df4ceb455baec356199a810e92c24dc626ad3611a6   (Repo Admin)
helm-hook-v1.0   bb5c93216b3bb7480d5550d01d85c3931c20411ddc033386df7cbe73e6d63f23   belitzphilipp
helm-hook-v1.1   725ecde4e6ebed53149a6ca689c1cb7cc534a482be916e075f5122828ef8e174   belitzphilipp
signed           495079f059a9398471a2b3eb3c27c97b160282a7bf73bd8e7b5056aa5cbb2277   (Repo Admin)
v0.1             3636feca1aa20ffaa74961e0f0b96de38df27098c3fada262cbe11a19efc929b   (Repo Admin)
(...)
v2.1.2           d0b9a8abc57918d4475da1f5aad1dc419c00b03e96989a41aedc5780eed2795c   belitzphilipp

List of signers and their keys for docker.io/securesystemsengineering/connaisseur

SIGNER          KEYS
belitzphilipp   eca961d4c858
starkteetje     9e9b0084457b

Administrative keys for docker.io/securesystemsengineering/connaisseur

  Repository Key:	349e5fcbc1354dab9ff5c7de21c67db4ec1a55c07a6f92ddd71000152f971bd2
  Root Key:	fbca7b3fa93f6390ad0ed3c56431f777ce12efa35cca8e3f6c203d1b5ef76eaf
```
In our example, `belitzphilipp` and `starkteetje` are only delegations that can be used to sign images but Connaisseur requires the root public key to verify signatures (as only that can be used to verify the whole signature chain). There is also [docs on how to enforce delegations](https://sse-secure-systems.github.io/connaisseur/v2.1.2/validators/notaryv1/#enforcing-delegations), but that is a different topic.

So in case, the public key is the key of the delegation or repo admin but not the root key, you would have to extract and configure the root public key in the `helm/values.yaml`. There is different ways to get the root public key:

The simplest may be to use our tooling as described [here](https://sse-secure-systems.github.io/connaisseur/v2.1.2/validators/notaryv1/#enforcing-delegations). That should look similar to:
```bash
docker run --rm docker.io/securesystemsengineering/get-public-root-key -i 1xxxxxxx0.dkr.ecr.amazonaws.com/poc_repo -s notary-server.myintradomain.com:4443
```
This will yield the public key that needs to be added to the validator config. However, the tool only works with public notaries (which seems to be the case for you, as there is no auth configured). Otherwise, please see the notes [here](https://github.com/sse-secure-systems/connaisseur/discussions/252).

If you created the root public key locally on your machine, you could also try to extract it manually via:
- Go to your private docker trust folder `~/.docker/trust/private` and identify the root key. To do so, you can either go through the files and search for the one with `role: root` or `grep -r 'role: root'`.
- Copy this file to a new file `root-priv.key` and remove line with `role: root` and the following empty line.
- Generate the corresponding public key via `openssl ec -in root-priv.key -pubout -out root.pub`. You will be asked to enter your root password.
- The new `root.pub` contains your public key which you copy and set in `/helm/values.yaml`.
- To clean up, remove the `root-priv.key` and `root.pub` in `~/.docker/trust/private`.

Let me know if that helps!
