### DISCUSSION TITLE
k8s connaisseur-deployment pods goes down immediately

### DISCUSSION THREAD

**Discussion by prasanjit-enginprogam** [sse-secure-systems/connaisseur#311] [Q&A] [answered]
Hello All, 
         k8s pods are going down within a couple of seconds once connaisseur-install-webhook-job and connaisseur-bootstrap-sentinel pods are completed. 

I am using cosign (latest) and is following the [official document](https://sse-secure-systems.github.io/connaisseur/v2.1.2/getting_started/#deploy-connaisseur)

I used the main branch for helm deployment. 

Versions: 
*connaisseur* : v2.1.2
*k8s :* Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609" 

Output: 
```
NAME                                          READY   STATUS    RESTARTS   AGE     IP              NODE                                          NOMINATED NODE   READINESS GATES
pod/connaisseur-deployment-6db7c98c8d-b42p5   0/1     Running   0          3m17s   10.150.21.85    ip-10-150-21-60.us-west-2.compute.internal    <none>           <none>
pod/connaisseur-deployment-6db7c98c8d-jznpd   0/1     Running   0          3m17s   10.150.14.237   ip-10-150-14-222.us-west-2.compute.internal   <none>           <none>
pod/connaisseur-deployment-6db7c98c8d-kstsk   0/1     Running   0          3m17s   10.150.44.135   ip-10-150-41-22.us-west-2.compute.internal    <none>           <none>

NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE     SELECTOR
service/connaisseur-svc   ClusterIP   172.20.225.168   <none>        443/TCP   3m17s   app.kubernetes.io/instance=connaisseur,app.kubernetes.io/name=connaisseur

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE     CONTAINERS    IMAGES                                        SELECTOR
deployment.apps/connaisseur-deployment   0/3     3            0           3m17s   connaisseur   securesystemsengineering/connaisseur:v2.1.2   app.kubernetes.io/instance=connaisseur,app.kubernetes.io/name=conn
aisseur

NAME                                                DESIRED   CURRENT   READY   AGE     CONTAINERS    IMAGES                                        SELECTOR
replicaset.apps/connaisseur-deployment-6db7c98c8d   3         3         0       3m17s   connaisseur   securesystemsengineering/connaisseur:v2.1.2   app.kubernetes.io/instance=connaisseur,app.kubernetes.io/nam
e=connaisseur,pod-template-hash=6db7c98c8d

````

Logs
```
[2021-09-16 05:06:31,182] INFO: 10.150.41.22 - - [16/Sep/2021 05:06:31] "GET /health HTTP/1.1" 200 -
[2021-09-16 05:06:35,148] INFO: 10.150.41.22 - - [16/Sep/2021 05:06:35] "GET /ready HTTP/1.1" 500 -
[2021-09-16 05:06:36,182] INFO: 10.150.41.22 - - [16/Sep/2021 05:06:36] "GET /health HTTP/1.1" 200 -
[2021-09-16 05:06:40,152] INFO: 10.150.41.22 - - [16/Sep/2021 05:06:40] "GET /ready HTTP/1.1" 500 -
[2021-09-16 05:06:41,182] INFO: 10.150.41.22 - - [16/Sep/2021 05:06:41] "GET /health HTTP/1.1" 200 -
[2021-09-16 05:06:45,148] INFO: 10.150.41.22 - - [16/Sep/2021 05:06:45] "GET /ready HTTP/1.1" 500 -
[2021-09-16 05:06:46,182] INFO: 10.150.41.22 - - [16/Sep/2021 05:06:46] "GET /health HTTP/1.1" 200 -
[2021-09-16 05:06:50,149] INFO: 10.150.41.22 - - [16/Sep/2021 05:06:50] "GET /ready HTTP/1.1" 500 -
[2021-09-16 05:06:51,182] INFO: 10.150.41.22 - - [16/Sep/2021 05:06:51] "GET /health HTTP/1.1" 200 -
[2021-09-16 05:06:55,149] INFO: 10.150.41.22 - - [16/Sep/2021 05:06:55] "GET /ready HTTP/1.1" 500 -
````

**Comment by xopham** [comment, marked as answer]
Hi @prasanjit-enginprogam :wave:

That is strange. Do the pods ever become ready and then turn "non-ready"? What do you get when doing a `kubectl describe` on the pods?
Could you share your `helm/values.yaml` as well?

**Reply by xopham** [reply]
And did you have another version of Connaisseur installed before or attempted a `helm upgrade`?

**Reply by jvaidyan** [reply]
@prasanjit-enginprogam  Did you get this resolved. I get the same behavior when tried on openshift.

**Reply by xopham** [reply]
@prasanjit-enginprogam are you also using Openshift or OKD? If so, @jvaidyan 's discussion in #321 and comment may help you: https://github.com/sse-secure-systems/connaisseur/discussions/321#discussioncomment-1411207

Let me know if that helps!

**Reply by gals-ma** [reply]
Hi, this same exact issue is happening to me as well when trying to install Connaisseur on k8s with cosign..
Any help will be appreciated!!

**Reply by xopham** [reply]
@prasanjit-enginprogam @jvaidyan @gals-ma thanks for reaching out!

We are implementing some major improvements in the upcoming release v2.2.0 that also aim to improve compatibility and resolve some of the installation issues. We still need to fix some minor problems that were found during testing already, but hope to release it within the next 2 weeks :partying_face: 

I prepared a release candidate for you that is not the final version, but would help us see whether it resolves your issues. To test it, please follow the steps below:

1. Switch to the [test/release-candidate-v2.2.0](https://github.com/sse-secure-systems/connaisseur/tree/test/release-candidate-v2.2.0) branch.
2. Make sure to remove all prior Connaisseur resources, e.g. `make annihilate` or follow [the docs on deleting](https://sse-secure-systems.github.io/connaisseur/develop/basics/#delete).
3. Depending on your Kubernetes version (e.g. <v1.19) or flavor (e.g. Openshift), adjust the [securityContext in `helm/values.yaml`](https://github.com/sse-secure-systems/connaisseur/blob/test/release-candidate-v2.2.0/helm/values.yaml#L30). The fields in questions contain comments on needed changes.
4. Install connaisseur, e.g. `make install` or follow [the docs on deploying](https://sse-secure-systems.github.io/connaisseur/develop/basics/#deploy). Connaisseur should come up much quicker than before.
5. Once Connaisseur has come up, `kubectl get all -n connaisseur` should show the resources as described [in the docs on checking](https://sse-secure-systems.github.io/connaisseur/develop/basics/#check).
6. Test Connaisseur using the following test images (notary v1 and cosign):
```bash
# cosign-based signatures
kubectl run cosigned --image=xoph/demo:signed   # is accepted
kubectl run counsigned --image=xoph/demo:unsigned   # is denied

# notary-based signatures
kubectl run signed --image=docker.io/securesystemsengineering/testimage:signed  # is accepted
kubectl run unsigned --image=docker.io/securesystemsengineering/testimage:unsigned  # is denied
```

Please let me know, if that works for you or whether you encounter any issues during installation. If something fails, please share your logs via `kubectl describe` and/or `kubectl logs` of failing components.

Hope this helps :slightly_smiling_face:

**Reply by gals-ma** [reply]
Hi @xopham ,
The problem was with PSP on our cluster.
Hope this helps others.

**Reply by xopham** [reply]
@gals-ma was it lack of a PSP and did the provided PSP flag below securityContext help?

**Reply by gals-ma** [reply]
@xopham 
It was restrictive PSP that was preventing us from deploying root containers.
After removing PSP it worked

**Reply by gals-ma** [reply]
@xopham - NVM, maybe not.
Still not working.
For some reason, like 1 out of 10 installs work and the rest have the same error as this issue.

**Reply by xopham** [reply]
@gals-ma did you test it with the release candidate above?
What is your k8s flavor? Which k8s version? Is there any logs on this?

**Reply by gals-ma** [reply]
@xopham yes, got the following error :
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "seccompProfile" in io.k8s.api.core.v1.SecurityContext`
K8s version 1.21.0

**Reply by xopham** [reply]
@gals-ma that sounds like an error you would get with k8s <v1.19 where the `seccomp` flag did not yet exist for securityContext. Can you try commenting/removing the [seccomp lines in `helm/values.yaml`](https://github.com/sse-secure-systems/connaisseur/blob/test/release-candidate-v2.2.0/helm/values.yaml#L40)? That should fix this.

**Reply by gals-ma** [reply]
looks like it was fixed
However, we are not getting an error when setting the detectivemode=true..
WDYT?

**Reply by xopham** [reply]
did you check everything is working with the testimages above?

for detection mode: you did set `detectionMode: true`? What error do you get? Just tested and it works for me.

**Reply by gals-ma** [reply]
@xopham 
`[2021-10-11 12:58:58,387] INFO: No alerting configuration file found.To use the alerting feature you need to run make upgradein a freshly pulled Connaisseur repository. [2021-10-11 12:58:58,387] ERROR: Traceback (most recent call last): File "/app/connaisseur/flask_server.py", line 50, in mutate response = __admit(admission_request) File "/app/connaisseur/flask_server.py", line 113, in __admit image in admission_request.wl_object.parent_containers.values() File "/app/connaisseur/workload_object.py", line 61, in parent_containers parent = k_api.request_kube_api( File "/app/connaisseur/kube_api.py", line 22, in request_kube_api response.raise_for_status() File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.100.0.1:443/apis/argoproj.io/v1alpha1/namespaces/coinmaster/rollouts/hello-world`

**Reply by xopham** [reply]
@gals-ma that looks like an authorization problem. It seems you are using ArgoCD which uses the CRD `rollouts` and Connaisseur is not configured to have access or check these resources. This causes a problem with [automatic child approval (ACA)](https://sse-secure-systems.github.io/connaisseur/develop/features/automatic_child_approval/).
You might be able to fix this by turning ACA off setting `automaticChildApproval.enabled: false`. This can only be done for the release candidate `v2.2.0`.
Does that work for you?

**Reply by gals-ma** [reply]
@xopham 
Well, it worked.
However, I cannot deploy signed images.
What I did is -
Added the public key to values.yaml.
Signed an image in my ECR with the corresponding private key.
Pulled the image to my endpoint.
did kubectl run on the image.
got the following error : 
```
❯ kubectl run cosigned --image 12341234.dkr.ecr.us-east-1.amazonaws.com/gal-signing-imagest-test:latest
Error from server: admission webhook "connaisseur-svc.connaisseur.svc" denied the request: Unexpected Cosign exception for image "12341234.dkr.ecr.us-east-1.amazonaws.com/gal-signing-imagest-test:latest": error: GET https://12341234.dkr.ecr.us-east-1.amazonaws.com/v2/gal-signing-imagest-test/manifests/latest: unexpected status code 401 Unauthorized: Not Authorized
```

**Reply by gals-ma** [reply]
My values.yaml file:
```
# configure Connaisseur deployment
deployment:
  replicasCount: 3
  image: xoph/connaisseur:rc-v2.2.0
  imagePullPolicy: IfNotPresent
  failurePolicy: Fail  # use 'Ignore' to fail open if Connaisseur becomes unavailable
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - connaisseur
            topologyKey: kubernetes.io/hostname
          weight: 100
  #annotations:  # uncomment when using Kubernetes prior v1.19
  #  seccomp.security.alpha.kubernetes.io/pod: runtime/default  # uncomment when using Kubernetes prior v1.19
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 10001  # remove when using openshift or OKD 4
    runAsGroup: 20001  # remove when using openshift or OKD 4
    # seccompProfile:  # remove when using Kubernetes prior v1.19, openshift or OKD 4
    #   type: RuntimeDefault  # remove when using Kubernetes prior v1.19, openshift or OKD 4
  # PodSecurityPolicy is deprecated as of Kubernetes v1.21, and will be removed in v1.25
  podSecurityPolicy:
    enabled: false
    name: ["connaisseur-psp"]  # list of PSPs to use, "connaisseur-psp" is the project-provided default

# configure Connaisseur service
service:
  type: ClusterIP
  port: 443

### VALIDATORS ###
validators:
# static validator that allows each image
- name: allow
  type: static
  approve: true
# static validator that denies each image
- name: deny
  type: static
  approve: false
# the `default` validator is used if no validator is specified in image policy
- name: defaultpolicy
  type: cosign  # or other supported validator (e.g. "cosign")
  trust_roots:
  # the `default` key is used if no key is specified in image policy
  - name: cosignkey
    key: |  # enter your key below
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjdpsv8IgdksYH+o0pHvJhIWJG7K9
      Q4x5M2H5kOaDyNosQUIlMgnIrpeSPWjZ00RBDF6JUMsX/KWyFV6EIBI63g==
      -----END PUBLIC KEY-----

# pre-configured nv1 validator for public notary from Docker Hub
- name: dockerhub-basics
  type: notaryv1
  host: notary.docker.io
  trust_roots:
    # public key for official docker images (https://hub.docker.com/search?q=&type=image&image_filter=official)
    # !if not needed feel free to remove the key!
  - name: docker-official
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOXYta5TgdCwXTCnLU09W5T4M4r9f
      QQrqJuADP6U7g5r9ICgPSmZuRHP/1AYUfOQW3baveKsT969EfELKj1lfCA==
      -----END PUBLIC KEY-----
  # public key securesystemsengineering repo including Connaisseur images
  # !this key is critical for Connaisseur!
  - name: securesystemsengineering-official
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsx28WV7BsQfnHF1kZmpdCTTLJaWe
      d0CA+JOi8H4REuBaWSZ5zPDe468WuOJ6f71E7WFg3CVEVYHuoZt2UYbN/Q==
      -----END PUBLIC KEY-----
  # public key for the release candicate v2.2.0
  - name: xoph-official
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEk/39kDS92/3MAhRu4+BTWAVOY5Ri
      LRtSpUx0DnVVQ4odJ+nhEvzvMeMHyU1WSG3rsoYaOFOMgoZFpiwjn2LqNg==
      -----END PUBLIC KEY-----

### IMAGE POLICY ###
# the image policy ties validators and images together whereby always only the most specific rule (pattern)
# is applied. specify if and how images should be validated by which validator via the validator name.
policy:
- pattern: "*:*"
- pattern: "370.dkr.ecr.us-east-1.amazonaws.com/*:*"
  validator: defaultpolicy
  with:
    trust_root: cosignkey
- pattern: "*370.dkr.ecr.us-east-1.amazonaws.com/*:*"
  validator: defaultpolicy
  with:
    trust_root: cosignkey
- pattern: "docker.io/library/*:*"
  validator: dockerhub-basics
  with:
    trust_root: docker-official
- pattern: "k8s.gcr.io/*:*"
  validator: allow
- pattern: "docker.io/securesystemsengineering/*:*"
  validator: dockerhub-basics
  with:
    trust_root: securesystemsengineering-official
- pattern: "docker.io/xoph/connaisseur:rc-*"
  validator: dockerhub-basics
  with:
    trust_root: xoph-official

detectionMode: false

namespacedValidation:
  enabled: false
  mode: ignore  # 'ignore' or 'validate'

# TODO: document ACA
automaticChildApproval:
  enabled: false
```

**Reply by xopham** [reply]
@gals-ma that looks like an authentication problem with ECR. I would presume you need to provide a secret reference under [the `auth` flag](https://sse-secure-systems.github.io/connaisseur/v2.1.2/validators/sigstore_cosign/#configuration-options). There is more information how to do that [in the docs](https://sse-secure-systems.github.io/connaisseur/v2.1.2/validators/sigstore_cosign/#authentication).

**Reply by gals-ma** [reply]
Hey @xopham , 
We have IAM Role attached to the ECR repository that allows the node itself all API calls to ECR.
Isn't it a better workaround?
Still, does not work. getting the same error.
Appreciate all the commitment here as this is the final blocker for us :(.
Any idea what we can do here?
The secret is a bit tricky for us in terms of security..

**Reply by gals-ma** [reply]
If we cancel Connaisseur we are able to pull and push images with the relevant ECR repo

**Reply by xopham** [reply]
@gals-ma did you update to the latest release v2.3.0 from Friday?

I'd presume that the node exhibits the service role, but would not know how the Connaisseur Pod would get access to the role of the node.
Do you have the option to use credentials that you could provide to Connaisseur?
Or how is that configured in your `.docker/config.json`?

**Reply by gals-ma** [reply]
I think that since Connaisseur is using a service account then the node's IAM role does has no effect on the pods.
This is the content of my local config.json file (i did not find it in the nodes) - 
{
	"auths": {
		"******.dkr.ecr.us-east-1.amazonaws.com": {},
		"******.dkr.ecr.us-east-1.amazonaws.com": {}
	},
	"credsStore": "desktop"
}%

**Reply by xopham** [reply]
Is that redacted of credentials? Like are there secrets in it? probably base64 encoded?
It seems to me that [ECR rotates those creds every 12h](https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/) and one would have to see how to find a stable solution, but [providing the configjson to connaisseur](https://sse-secure-systems.github.io/connaisseur/v2.2.0/validators/sigstore_cosign/#authentication) to see whether that solves the issue would at least make sure it is actually an auth problem.

**Reply by xopham** [reply]
At least when I try to verify your image using Cosign without access to credentials, I get the same message:
```bash
error: GET https://12341234.dkr.ecr.us-east-1.amazonaws.com/v2/gal-signing-imagest-test/manifests/latest: unexpected status code 401 Unauthorized: Not Authorized
```
This is however the same response as for a non-existent registry...

**Reply by gals-ma** [reply]
did you update to the latest release v2.3.0 from Friday?
**Yes, I'm using master (FYI, my k8s version is 1.18 if that mean anything**
Is that redacted of credentials? Like are there secrets in it? probably base64 encoded?
**I sent the original content of my config.json file, not really sure what should be there to be honest..**

Would it help if we remove the Connaisseur service account and the pods will inherit the Nodes permissions and should get access to our ECR with an IAM role attachment?
As for creating the secret, i tried the following:
`kubectl create secret generic mysecret --from-file=.dockerconfigjson=/Users/gal/.docker/config.json --type=kubernetes.io/dockerconfigjson -n connaisseur`
secret was created but still got the same 401 error..
```
kubectl describe secrets -n connaisseur mysecret
Name: mysecret
Namespace: connaisseur
Labels:
Annotations:

Type: kubernetes.io/dockerconfigjson
```

**Reply by gals-ma** [reply]
Removing the service account did not help too :S

**Reply by xopham** [reply]
To test whether providing creds works, you will probably have to follow the aws guide to get a local docker login and thus proper dockerconfigjson: https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry_auth.html#registry-auth-token
This could then be provided to connaisseur and should at least for 12 hours allow you to validate images: https://sse-secure-systems.github.io/connaisseur/v2.2.0/validators/sigstore_cosign/#authentication

**Reply by xopham** [reply]
@gals-ma I did a test of my own:
1. setup an EKS Cluster according to: https://docs.aws.amazon.com/eks/latest/userguide/getting-started-console.html
2. added fargate nodes configs for namespaces `default`, `connaisseur` and `kube-system` and restarted the default addons (coredns, kubeproxy, vpc-cni) -> running system
2. setup a private repository on ECR according to: https://docs.aws.amazon.com/AmazonECR/latest/userguide/getting-started-console.html
3. to setup my local docker config, I followed step 1&2 of "Build, tag, and push a Docker image" of: https://docs.aws.amazon.com/AmazonECR/latest/userguide/getting-started-console.html
4. as a result my `~/.docker/config.json` looks somewhat like the following:
```json
{
	"auths": {
		"1234567890.dkr.ecr.us-west-2.amazonaws.com": {
			"auth": "<some-long-base64-string>"
		}
	}
}
```
5. I added that `.docker/config.json` as a kubernetes secret and configured connaisseur to use it for the respective validator according to: http://localhost:8000/validators/sigstore_cosign/#authentication . 
6. I can check the secret via `k get secrets -n connaisseur my-secret -o yaml`
7. The respective validator and policy sections in my `helm/values.yaml` configuration look like:
```yaml
(...)
validators:
(...)
- name: my-validator
  type: cosign
  auth:
    secret_name: my-secret
  trust_roots:
  - name: my-key
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEef/kKgv5UpTbZO2hxMoUdrwdwIbo
      V2W5yzBlbxGLKjslcImDVxuOEEBdZNkJce10LD2hypqkL2VLiMP8a2heWA==
      -----END PUBLIC KEY-----
(...)
policy:
- pattern: "*:*"
  validator: my-validator
  with:
    trust_root: my-key
(...)
```
8. pushed some image to my ECR, e.g.: `docker push 1234567890.dkr.ecr.us-west-2.amazonaws.com/my-ecr:demo`
9. Running it unsigned was denied as expected: `kubectl run demo --image=1234567890.dkr.ecr.us-west-2.amazonaws.com/my-ecr:demo`
10. Signing it with cosign and running it again was admitted.

So that works nicely for me! In fact, I even tried without steps 5-7 which gives the same error as you had. So it is indeed authentication.

There is one caveat: Step 3 refers to AWS docs that already indicate that "_This command provides an authorization token that is valid for 12 hours._". So, I suppose that when I try again tomorrow my previously created dockerconfigjson won't work anymore.
Will try to figure out tomorrow whether there is some sort of technical role or something available in AWS ECR to get a long-lived authorization token or something.
