### DISCUSSION TITLE
slack integration: alerts per image policy enhancement request?

### DISCUSSION THREAD

**Discussion by tommyreilly** [sse-secure-systems/connaisseur#384] [Ideas]
Hi,

Wondering if this use case makes sense and how feasible it may be to accept this as an enhancement request.

I've successfully configured the existing slack integration such that for all workloads (for all image policies), admit_requests and reject_requests go to a single slack channel (I know that it can be configured to have a different receiver_url for each).

However, for my companies use case, we have many of our product teams using the same k8s (GKE) cluster. Each product teams would have their own image policy defined in connaisseur values.yaml. For example:

```
policy:
- pattern: "*:*"
  validator: deny
- pattern: "gcr.io/product-team-a-url-*.*"
  validator: my-company-teams
  with:
    trust_root: product-team-a
- pattern: "gcr.io/product-team-b-url-*.*"
  validator: my-company-teams
  with:
    trust_root: product-team-b
```

with the my-company-teams validator having the relevant product team public keys for product-team-a and product-team-b.

What I would ideally like to offer our product teams is that alerts specific to their deployments would be sent to their own slack channel - i.e. product-team-a gets admit/reject request notifications for their workloads matching their image policy to their product-team-a slack channel and separately product-team-b gets admit/reject request notifications for their workloads matching their image policy to their product-team-b slack channel.

Hope this request makes sense and is seen as practical. Unsure of how difficult it would be to implement and would, presumably require additional configuration settings.

Thanks

Tommy
