### DISCUSSION TITLE
Caching for same image verification vs automatic child approval

### DISCUSSION THREAD

**Discussion by mathuvenkat** [sse-secure-systems/connaisseur#636] [Q&A] [answered]
Is there any caching involved when specs refer to the same image which has been validated ?
i.e image is referenced by tag in the spec say image:tagA , mutating admission webhook changes it to image:digestA and verifies signature. For a different spec with image:tagA, will process be repeated or after it mutates to digest is there any understanding that it has been validated earlier ? How is automatic child approval related to this if at all ? 

Second question is regarding secrets, to use connaisseur in our cluster for infra as well as tenant namespaces, we should have ability of tenant images being able to be verified by their own keys vs infra images verified by a different key. This is possible using policy patterns and validators to indicate different keys for different image prefix/pattern. If images were from different registries , can we specify auth for each validator ? 

https://sse-secure-systems.github.io/connaisseur/v2.1.2/validators/sigstore_cosign/#authentication - "It is possible to provide one Kubernetes secret with a config.json for authentication to multiple private registries and referencing this in multiple validators." 
Eg: is this right ? 
```yaml
--- 
policy: 
  - 
    pattern: "quay.io/team/component*:*"
    validator: infra-imagevalidator
    with: 
      key: key1
  - 
    pattern: "tenant.registry/team/component*:*"
    validator: tenant-imagevalidator
    with: 
      key: key1
validators: 
  - 
    auth: 
      secret_name: quay-secret
    name: infra-imagevalidator
    trust_roots: 
      - 
        key: |
            -----BEGIN PUBLIC KEY-----
            -----END PUBLIC KEY-----
        name: key1
    type: cosign
  - 
    auth: 
      secret_name: tenant-registry-secret
    name: tenant-imagevalidator
    trust_roots: 
      - 
        key: |
            -----BEGIN PUBLIC KEY-----
            -----END PUBLIC KEY-----
        name: key1
    type: cosign

```
