### DISCUSSION TITLE
Unexpected Cosign exception

### DISCUSSION THREAD

**Discussion by prasadjlv** [sse-secure-systems/connaisseur#679] [Q&A]
Hello: 

I have deployed connaisseur v2.6.0 in an EKS cluster that uses private docker registry (ECR). My validators and policy snippets are simple (redacted) as shown below:
 
```
validators:
  - name: cosign-validator
    type: cosign
    auth:
      secret-name: my-secret
    trust_roots:
      - name: my-key
        key: awskms:///arn:aws:kms:us-east-1:123456789012:alias/cosign-poc

policy:
  - pattern: "123456789012.dkr.ecr.us-east-1.amazonaws.com/*:*"
    validator: cosign-validator
    with:
      trust_root: my-key   
```

I have used the dockerconfigjson to create the secret (my-secret) and I have set the logLevel to DEBUG.

Deployment of a signed image from our docker registry fails with:
Error from server: admission webhook "connaisseur-svc-connaisseur.svc" denied the request: Unexpected Cosign exception for image "123456789012.dkr.ecr.us-east-1.amazonaws.com/poc/demo:latets": Error: no matching signatures

I have verified the image using "cosign verify --key ", so maybe I am doing something wrong. Please help me debug the above issue.
