### ISSUE TITLE
Slow memory leak causing cosign subprocess termination

### ISSUE THREAD

**Issue by sbeck14** [sse-secure-systems/connaisseur#1090]
**Describe the bug**
<A clear and concise description of what the bug is.>

We have connaisseur `2.8.0` deployed in Kubernetes using a Helm install, and after running normally for a while (between a few days to a week) we start seeing Connaisseur reject images and producing these errors in the logs:

```
INFO: COSIGN output of trust root 'default' for image'[redacted]': RETURNCODE: -9; STDOUT: ; STDERR:
INFO: {'message': 'Unexpected Cosign exception for image "[redacted]": .', 'context': {'trust_data_type': 'dev.cosignproject.cosign/signature', 'stderr': '', 'image': '[redacted]', 'trust_root': 'default', 'detection_mode': False}}
```

Upon inspection of the memory usage of the Connaisseur pods, it appears that the memory usage of the Connaisseur process slowly rises over time, indicating a memory leak.

Result of `ps` command on a pod immediately after launching

```
PID   USER     VSZ  RSS  COMMAND          COMMAND
    1 10001     60m  45m python           python -m connaisseur
   18 10001    1684 1072 sh               /bin/sh
   24 10001    1608  984 ps               ps -o pid,user,vsz,rss,comm,args
```

Result of `ps` command on a pod running for ~7 days

```

PID   USER     VSZ  RSS  COMMAND          COMMAND
    1 10001    317m 302m python           python -m connaisseur
 4827 10001    1692 1060 sh               /bin/sh
 4835 10001    1616  984 ps               ps -o pid,user,vsz,rss,comm,args
```

Once the memory usage approaches the memory limit on the pod, our theory is that Kubernetes begins killing the cosign sub-process immediately after it spawns because it causes the pod to exceed the memory limit. Afterwards, the main Connaisseur process reports the error and the memory usage continues growing until Kubernetes finally kills the main process, restarting the pod.

**Expected behavior**
<A clear and concise description of what you expected to happen.>

Connaisseur process memory does not grow and stays about the same over time

**Optional: To reproduce**
<Stepwise guide or instructions or minimal example to reproduce.>

I haven't been able to reliably reproduce this without just waiting for the memory to grow over time. I tried restarting the deployment and hitting the API with an `AdmissionReview` 3000x in a row, but the memory usage only increased by about 10 mb. I also tried this with different types of `AdmissionReview` (static verifier, cosign, and automatic child approval) with similar results.

**Optional: Versions (please complete the following information as relevant):**
 - Kubernetes Cluster: Kubernetes v1.21.9
 - Container registry: Gitlab Enterprise
 - Connaisseur: v2.8.0

**Comment by sbeck14** [comment]
Here are our policies & validators from our helm `values.yaml`:

```
validators:
  - name: default
    type: static
    approve: true
  - name: gitlab
    type: cosign
    auth:
      secret_name: gitlab
    trust_roots:
    - name: default
      key: awskms:///[redacted]
policy:
- pattern: "*:*"
- pattern: "[redacted domain]/*:*"
  validator: gitlab
  with:
    trust_root: "*"
    threshold: 1
```
