### ISSUE TITLE
Using cosign validation works for about 6 hours and then we start getting validation errors for Connaisseur application version 3.6.1 and chart version 2.6.1

### ISSUE THREAD

**Issue by edison-vflow** [sse-secure-systems/connaisseur#1765]
**Describe the bug**
<A clear and concise description of what the bug is.>
When using Connaisseur application version 3.6.1 and chart version 2.6.1 on EKS v1.30, using cosign validators  where auth.secretName is used and ECR is the image registry, Connaisseur can validate images correctly and after about 6 hrs, validation starts failing with 

```
{
  "level": "error",
  "msg": "error validating Deployment ABCD: error during cosign validation of image AWS_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/APPLICATION: error validating image: [GET https://AWS_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/v2/APPLICATION/manifests/*****: DENIED: Your authorization token has expired. Reauthenticate and try again.]",
  "time": "2024-09-20T16:45:00Z"
}

```

The validator section is defined as 
```
application:
  validators:
  - name: awsvalidator
    type: cosign
    auth:
      secretName: 'ecr-credentials'
    trustRoots:
    - name: ecr-cosign
      key: ${container_verification_kms_arn}
  - name: allow
    type: static
    approve: true
  - name: deny
    type: static
    approve: false
```
The issue happens for the `awsvalidator` that needs ECR credentials provided via the secret `ecr-credentials`
On initial run , validation works for about 6 hrs.This time sometimes varies.

After the 6 or so hours, we start getting the error highlighted above.

At the moment that validation starts failing, various operations in the cluster are blocked, like rollout of deployments. 

What we notice is that if we restart Connaisseur, then validation starts working again, until the next expiration.

We have a cronjob that runs every 6 hrs, this is to cater for the fact that the ECR token expires after 12 hrs.
This refresh ecr cronjob refreshes the ecr-credentials secret that Connaisseur validator is using.
For refreshing the token every 6 hrs before expiration, we are using https://github.com/nabsul/k8s-ecr-login-renew
The refreshing seems to be working, as the restart of  Connaisseur always works and the restart will be using this refreshed token.

Its looking like the Connaisseur validator that uses the auth.secret mechanisms reads the token in once at startup but does not have a way of reading the token when it is refreshed in the ecr-credentials secret, the same secret it is reading from at start-up.

Would this explain why a restart of Connaisseur seems to always fix the issue ?

Another test we did is to explicitly run the token renewal job at the time Connaisseur validation fails to force token refresh.
The credentials are renewed but they are not picked up by a running instance of Connaisseur 

Could you give guidance on how best to solve this issue or perhaps what other clients that are using the auth.secret for cosign are doing to always have Connaisseur use the latest token 

**Expected behavior**
<A clear and concise description of what you expected to happen.>
* When Connaisseur cosign validation works initially, it should continue working even after token expiration of the initial token it read in, with an ability to refresh the token and not that Connaisseur should be manually restarted  for the new token to be picked up

**Optional: To reproduce**
<Stepwise guide or instructions or minimal example to reproduce.>
To reproduce, install Connaisseur application version 3.6.1 and chart version 2.6.1 on AWS EKS v1.30
Configure your validators section as shown above.
This is a setup where the trust roots are taken from KMS and the cosign is using auth.secret where the secret is using the [dockerconfigjson](https://sse-secure-systems.github.io/connaisseur/v3.6.1/validators/sigstore_cosign/#dockerconfigjson) mechanism  

**Optional: Versions (please complete the following information as relevant):**
 - OS: Amazon Linux 
 - Kubernetes Cluster: EKS 1.30
 - Notary Server: <notary and version>
 - Container registry: containerd
 - Connaisseur: chart 2.6.1 application 3.6.1
 - Other: <other relevant tools and versions>

**Optional: Additional context**
* The same deployment also shows redis erros in the redis pod.
Not sure if this affects the validation somehow but just worth mentioning 
The redis issue was raised separately as its own issue
https://github.com/sse-secure-systems/connaisseur/issues/1764

**Comment by edison-vflow** [comment]
cc @phbelitz @chrysogonus

**Comment by edison-vflow** [comment]
@phbelitz @chrysogonus , another way this could be fixed with less effort is to allow the Connaisseur deployment to add custom annotations from the `values.yam`l file.

Currently the annotations that can be added on a deployment are restricted 

If we can allow custom annotations here 

https://github.com/sse-secure-systems/connaisseur/blob/c040f4d4a31394de5c53408fc770978c080b5876/charts/connaisseur/templates/deployment.yaml#L8

Then we can use something like https://github.com/stakater/Reloader
where we add the annotation 
```
    reloader.stakater.com/auto: "true"

```
I see that the ecr-credentials secret ends up being included in the deployment as a volume mount, which makes it a perfect candidate for Reloader to restart the deployment 

```
volumes:
        - name: certs
          secret:
            secretName: connaisseur-tls
        - name: redis-certs
          secret:
            secretName: connaisseur-redis-tls
        - name: app-config
          configMap:
            name: connaisseur-app-config
        - name: connaisseur-alert-config
          configMap:
            name: connaisseur-alert-config
        
        - name: ecr-credentials-volume
          secret:
            secretName: ecr-credentials
```

I have played around with this idea further by manually editing the Connaisseur deployment to add Reloader annotations 

### There were 2 outcomes.
1. Using  https://github.com/nabsul/k8s-ecr-login-renew will not work in its current state.The utility creates a brand new secret called `ecr-credentials`.Reloader on the other hand can actually do a rollout to a deployment when either a configmap or a secret its using are changed.This does not include when the secret is destroyed and recreated 
2. I did a second test whereby instead of refreshing the `ecr-credentials` secret the way https://github.com/nabsul/k8s-ecr-login-renew does it, we actually modify the value of the existing secret.This worked perfectly and the Connaisseur deployment was restarted, able to refresh the token from the modified secret 

So this is to just share ideas on one way token refresh could be achieved when using the `auth.secretName`  validators mechanism
