### ISSUE TITLE
Pod disruption budget

### ISSUE THREAD

**Issue by ricfo-tricentis** [sse-secure-systems/connaisseur#1850]
**Describe the feature**
When we are upgrading the cluster or adding/removing node pools, we are getting error that new image cannot be pulled because the connaisseur service is not available. The solution is either to uninstall the helm chart before the operation and install it back after, or use pod disruption budget like following:

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: connaisseur
  namespace: connaisseur
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: connaisseur
```

**Optional: Is your feature request related to a problem? Please describe.**
<A clear and concise description of what the problem is.>

**Optional: Implementation ideas**
<Maybe you already have an implementation and alternatives in mind. Please share your thoughts.>

**Optional: Additional context**
<Add any other context or screenshots about the feature request here.>
I would follow this link, but I'm lazy atm. https://awjunaid.com/kubernetes/how-to-implement-pod-disruption-budgets-with-helm-in-kubernetes/
