### ISSUE TITLE
ImageRef is mutated with the wrong digest

### ISSUE THREAD

**Issue by funkypenguin** [sse-secure-systems/connaisseur#583]
**Describe the bug**

This issue may be precipitated by https://github.com/sse-secure-systems/connaisseur/issues/582. Our CI platform routinely deploys about 40 pods into a fresh namespace to test code changes. We noticed that after deploying connaisseur, some of the time, the pods in these namespaces fail with an error like this:

```
  Warning  Failed       12s                kubelet            Failed to pull image "docker.io/gergorg/rtdb@sha256:8f76cb854b018213597d910fb4a1ad7d5d5ed775fbe328594b9d6347a48c38f9": rpc error: code = NotFound
 desc = failed to pull and unpack image "docker.io/myorg
/rtdb@sha256:8f76cb854b018213597d910fb4a1ad7d5d5ed775fbe328594b9d6347a48c38f9": failed to resolve reference 
"docker.io/myorg/rtdb@sha256:8f76cb854b018213597d910fb4a1ad7d5d5ed775fbe328594b9d6347a48c38f9": docker.io
/myorg/rtdb@sha256:8f76cb854b018213597d910fb4a1ad7d5d5ed775fbe328594b9d6347a48c38f9: not found
```

The digest ref is the result of a deployment being mutated by connaisseur, having the image tag changed into the digest format. 

**However**... the actual digest applied belongs to a **different** image in a **different** repository, which was deployed by CI at the same time into the namespace:

<img width="329" alt="Harbor 2022-03-17 16-26-56" src="https://user-images.githubusercontent.com/1524686/158740945-b2971825-7ec2-41e2-b2d7-95ed7f204cf2.png">

It would seem that connaisseur "mixed up" the digests of the various deployments/pods which were deployed at the same time (potentially due to an error parsing the CRs), and substituted the digest for one image, with another.

**Expected behavior**

Connaisseur only mutates imageRefs matching the repository and image which was originally intercepted

**Optional: To reproduce**

This is hard, since the issue seems to be intermittent. It **seems** to co-inside with the errors generated by https://github.com/sse-secure-systems/connaisseur/issues/582. To reproduce, try deploying about 20 different images simultaneously, mixed in with some CRDs which include an image ref.

**Optional: Versions (please complete the following information as relevant):**
 - Connaisseur: 2.5.1

**Comment by xopham** [comment]
@funkypenguin that indicates a potentially very problematic issue. Will start triangulation of the root cause. Would you mind to share a (redacted version of) `helm/values.yaml` and some more information about the deployment. Do you apply many pods in one deployment or many deployments with single pods?

**Comment by funkypenguin** [comment]
Thanks @xopham,

We're using cosign as a validator, against a private registry. 

The non-default elements of `helm/values.yaml` are as follows (_you'll notice some ansible variables used in our deployment_):

```
deployment:
  image: myorg/connaisseur:{{ packages.connaisseur.version.image }} # we mirror the container to our own registry
  envs:
    AWS_REGION: "{{ cosign_awskms_kms_region }}"
    AWS_SECRET_ACCESS_KEY: "{{ cosign_awskms_iam_secret_key }}"
    AWS_ACCESS_KEY_ID: "{{ cosign_awskms_iam_access_key }}"
    AWS_CMK_ID: "alias/{{ cosign_awskms_kms_key_alias }}"

  annotations: 
    configmap.reloader.stakater.com/reload: "connaisseur-env,connaisseur-config,connaisseur-alert-templates,connaisseur-alertconfig"
    secret.reloader.stakater.com/reload: "registry-credentials"

policy:
  - pattern: "*:*"
  - pattern: "docker.io/library/*:*"
    validator: default
    with:
      trust_root: default
  - pattern: "docker.io/myorg/*:*"
    validator: default
    with:
      trust_root: default      
  - pattern: "k8s.gcr.io/*:*"
    validator: allow
  - pattern: "docker.io/securesystemsengineering/*:*"
    validator: dockerhub-basics
    with:
      trust_root: securesystemsengineering-official

detectionMode: true

automaticChildApproval:
  enabled: false

logLevel: WARNING

validators:
  # static validator that allows each image
  - name: allow
    type: static
    approve: true
  # static validator that denies each image
  - name: deny
    type: static
    approve: false
  # the `default` validator is used if no validator is specified in image policy
  - name: default
    type: cosign  # or other supported validator (e.g. "cosign")
    # host: notary.docker.io # in case of notaryv1, configure the notary server to be used
    auth: 
      secret_name: registry-credentials  # reference a k8s secret in the form required by the validator type (check the docs)
    trust_roots:
    # # the `default` key is used if no key is specified in image policy
    - name: default
      key: awskms:///alias/{{ cosign_awskms_kms_key_alias }}
```

In terms of our deployment, we use helm to install a single "umbrella" chart, which "requires" 10-20 sub-charts. Consequently, we end up with:

```
root@cowboy:~# k get pods -n preview-notifications-pr-8  | wc -l
48
root@cowboy:~# k get deployments.apps -n preview-notifications-pr-8 | wc -l
17
root@cowboy:~# k get statefulsets.apps -n preview-notifications-pr-8 | wc -l
4
root@cowboy:~#
```

Included in these sub-charts are CRs for vault-operator, minio-operator, and fdb-operator. I should also note that we use istio, so each pod gets an envoy-proxy sidecar injected, but this seems to happen _after_ connaisseur's mutation, since the envoy-sidecar images are not mutated to use digests.

Happy to provide further feedback / testing as required :)

D
