### ISSUE TITLE
When creating a pod with a signed image, an error is reported: None is an unsupported authentication type in notary default

### ISSUE THREAD

**Issue by dugen2020** [sse-secure-systems/connaisseur#588]
### Discussed in https://github.com/sse-secure-systems/connaisseur/discussions/587

<div type='discussions-op-text'>

<sup>Originally posted by **dugen2020** March 21, 2022</sup>
When creating a pod with a signed image, an error is reported: None is an unsupported authentication type in notary default;
This problem has been bugging me for a long time.

The docker registry is harbor and the version is 2.2.2
```sh
#kubectl -n connaisseur get pods -o wide 
NAME                                     READY   STATUS    RESTARTS   AGE   IP             NODE           NOMINATED NODE   READINESS GATES
connaisseur-deployment-6db5cb959-jsbs6   1/1     Running   0          8h    100.80.182.106   172.16.18.38   <none>           <none>
```

Create a pod  through the signed image, there will be the following error logs 
```sh
#kubectl run demo --image=10.45.80.37/public/zcm-netshooting:check01
Error from server: admission webhook "connaisseur-svc.connaisseur.svc" denied the request: None is an unsupported authentication type in notary default.

```

There is no problem with the image signature, it is based on DCT
```sh 
#docker trust inspect --pretty 10.45.80.37/public/zcm-netshooting:check01
Signatures for 10.45.80.37/public/zcm-netshooting:check01
SIGNED TAG          DIGEST                                                             SIGNERS
check01             363d9cf253329d00d867c7a34881f2da9125e8ffcd40ac865ea7e257e1505f75   root
List of signers and their keys for 10.45.80.37/public/zcm-netshooting:check01
SIGNER              KEYS
root                a8960fc326fe
Administrative keys for 10.45.80.37/public/zcm-netshooting:check01
  Repository Key:       fd4365e527b5b8b3baac6e19d31fac81f3410e51030c76834138b55f5f64d2a5
  Root Key:     7a99b0f0435ddaaae8429f794c765d7dca2f110339a3d41ea43c56589687bf27
```

This problem has been bugging me for a long time, can anyone help me?

There is also an error in the console log of connaisseur
```sh
#kubectl -n connaisseur logs -f connaisseur-deployment-6db5cb959-jsbs6 
[2022-03-21 13:01:58,425] ERROR: {'message': 'None is an unsupported authentication type in notary default.', 'context': {'auth_type': None, 'notary_name': 'default', 'detection_mode': False, 'user': 'kubernetes-admin', 'operation': 'CREATE', 'kind': 'Pod', 'name': 'demo', 'namespace': 'default'}}
[2022-03-21 13:01:58,426] INFO: 100.80.102.128 - - [21/Mar/2022 13:01:58] "POST /mutate?timeout=30s HTTP/1.1" 200 -

```
The validator configuration is as follows
```yaml
validators:
  # static validator that allows each image
  - name: allow
    type: static
    approve: true
  # static validator that denies each image
  - name: deny
    type: static
    approve: false
  # the `default` validator is used if no validator is specified in image policy
  - name: default
    type: notaryv1  # or other supported validator (e.g. "cosign")
    host: 10.45.80.37 # in case of notaryv1, configure the notary server to be used
    trust_roots:
    # # the `default` key is used if no key is specified in image policy
    - name: default
      key: |  # enter your public key below
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnqAlXBYsmqLqXVW2d665Jo5oVryp
        Odvf8Pfl2lO3XhjIP5v7sj/oHuvfYMHUM4eM59LhL7/qUW9u0sqwfPDJcQ==
        -----END PUBLIC KEY-----
    cert: |  # in case the trust data host is using a self-signed certificate
      -----BEGIN CERTIFICATE-----
      MIIDvjCCAqagAwIBAgIUUYOizH8VhGivcg8vBc5kZVVws8swDQYJKoZIhvcNAQEL
      BQAwZTELMAkGA1UEBhMCQ04xEDAOBgNVBAgTB0ppYW5nU3UxEDAOBgNVBAcTB05h
     ... omit
     ...omit
      GCyKV1EJSo1hLdd6s8kTGJKdTZVAcKKEDy5FweNu4P01NctiBuZzzVg1rIovNZCP
      UW3uUd3iGuufmsN/v4jmeypY2A+vtpjC6UU5g6YE1nOA/hA45sqrx6Ls9TgiKM+i
      Gqs=
      -----END CERTIFICATE-----
    #auth:  # credentials in case the trust data requires authentication
    #  # either (preferred solution)
    #  secret_name: mysecret  # reference a k8s secret in the form required by the validator type (check the docs)
    #  # or (only for notaryv1 validator)
    #  username: myuser
    #  password: mypass
```

</div>
