### ISSUE TITLE
Installing the helm chart with argocd causes RepeatedResourceWarning

### ISSUE THREAD

**Issue by gigi206** [sse-secure-systems/connaisseur#764]
**Describe the bug**
```
RepeatedResourceWarning
Resource admissionregistration.k8s.io/MutatingWebhookConfiguration//connaisseur-webhook appeared 2 times among application resources.
```

**To reproduce**:
* Install ArgoCD
* Apply this file (`kubectl apply -f `)
```yaml
project: default
source:
  repoURL: 'https://sse-secure-systems.github.io/connaisseur/charts'
  targetRevision: 1.4.3
  helm:
    parameters:
      - name: deployment.replicasCount
        value: '1'
  chart: connaisseur
destination:
  server: 'https://kubernetes.default.svc'
  namespace: connaisseur
syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - PruneLast=true
```
